### ISSUE TITLE
Withdrawal issues

### ISSUE THREAD

**Issue by MrRGnome** [fiatjaf/etleneum#2]
Not sure what is causing these withdrawal issues or where to post this. Been trying to withdraw to multiple different nodes including ones with significant inbound liquidity such as phoenix wallet, but having no success at all.

https://github.com/etleneum/database/commits/master/accounts/04f944f399a786616879c8ff5473efbc21e16eeabab6577b794f3ba701dbbf3881f1062861580920cc472de1f8971cdf35f4409e9ae2d95b6d519797a5666f3217

Working somewhat blind as the only feedback I get is "payment failed". Any advice on how to withdraw the current balance in this account would be welcome.

**Comment by MrRGnome** [comment]
After painstakingly structuring a direct channel with elteneum I was able to make one successful withdrawal for about half my sats but now all attempts to contact the lnurl service timeout. Still having issues with trapped funds.

**Comment by fiatjaf** [comment]
Sorry, we're having some issues and will be back as soon as possible.

Also don't post your session keys like that or anyone will be able to steal your funds.

**Comment by MrRGnome** [comment]
I appreciate you removing that error on my part I was mistakenly under the impression it was the k1 value that was important. Today I learned.

Thanks for your attention on this issue. I'll patiently await the services return.

**Comment by MrRGnome** [comment]
This issue is resolved, thank you for your time and attention.

**Comment by fiatjaf** [comment]
Next time cone to https://t.me/etleneum and complain there.
