### ISSUE TITLE
Problems paying etleneum Chainmarket fees

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/etleneum#3]
This invoice had problems.  Couldn't pay it from my Etleneum balance, nor from various wallets or @lntxbot.

lnbc17600p1psncd5xpp5t56zxw6fvcxm0etaaxkw539ddqrqur3f3q568d74y0squr7armjqdzqv46xcetwv46k6gr50pek2mn5ypdkxwrhxp3nzvmkxu646kmjd33nwmfev3a8zd2axqyz5vqrzjqtqkejjy2c44jrwj08y5ygqtmn8af7vscwnflttzpsgw7tuz9r407qcr3rvsg6gcqqqqqqqqqqqqqqqqjqsp5qvpsxqcrqvpsxqcrqvpsxqcrqvpsxqcrqvpsxqcrqvpsxqcrqvps9qypqsqthkvpdnm8j7xaf84kcggz572hh3v23gzcwq2hrq84p0uq04wh58h8y9sknjwkpfut4mpnj8kgfxa4p6mvpwclvry9982mmmc6096lhcqah7mz8

And when I pay it, or any of the 1 sat fee to confirm "Notify a transaction was broadcasted" it fails with:
```
Your call failed: runtime error: <pre>error executing method: [string "call"]:99: attempt to index a nil value (local 'tx')
97 local offersmatched = 0
98
99 for _, vout in ipairs(tx.vout) do
100 local addr = vout.scriptpubkey_address
101 local offer = contract.state[addr]</pre>
```

```
Routes tried for 5d34233b49660db7e57de9acea44ad68060e0e298829a3b7d523e00e0fdd1ee4:
❌  channel is permanently unavailable
```
And the reservation on the checked offers expires and the offer is available for another taker.

The transaction paying bc1q3f7q8zn39q0vqnk79s9j4emfswl3h80d593xla 500,000 sats is https://www.blockchain.com/btc/tx/c1f440526fff79c96d12df2ae339a9d0498e114f3a40cdd2f3b6c1076db601e2

**Comment by HamishMacEwan** [comment]
Thanks.  All good.

**Comment by fiatjaf** [comment]
:roll_eyes:

**Comment by HamishMacEwan** [comment]
While it was possible to pay the fee, it remains not possible to "pay with Etleneum balance."  There is no response to pressing that button, while there is sufficient balance to pay.

**Comment by fiatjaf** [comment]
Should work now.

**Comment by HamishMacEwan** [comment]
Hmm, no response at [https://smt.etleneum.com/#/ck6wdx9uw000q8201df8nmm37](https://smt.etleneum.com/#/ck6wdx9uw000q8201df8nmm37)

Logged in.

No page rendered: [https://smt.etleneum.com/](https://smt.etleneum.com/)

**Comment by fiatjaf** [comment]
Sorry, my deployment script had a bug. Now it should work.
